### ISSUE TITLE
No multiplicities work for this -1 charged molecule when using ScfGradientDriver and OptimizationDriver

### ISSUE THREAD

**Issue by bc118** [kthpanor/echem#10]
No multiplicities work for this -1 charged molecule when using `ScfGradientDriver` and `OptimizationDriver`, but it seems to work if not using `ScfGradientDriver` and `OptimizationDriver` for other calculations.  Multiplicities 1 and 3 have previously worked on Gaussian for the same molecule.  I have attached the file and have tried many multiplicities when using:

```
grad_drv = vlx.ScfGradientDriver()
opt_drv = vlx.OptimizationDriver(grad_drv)
opt_molecule = opt_drv.compute(mol_vlx, bas_vlx, scf_drv)
```

Can you shed light on this or maybe point out what I am doing wrong?

[dihedral_test_working_CT_CT_C_O_mult_1_0_R_groups.zip](https://github.com/kthpanor/echem/files/11782892/dihedral_test_working_CT_CT_C_O_mult_1_0_R_groups.zip)

Also note, the attached file works for ethane and the protonated version of this attached molecule.

**Comment by recoli** [comment]
Thanks for reporting the issue. This should have been fixed in the latest conda build of veloxchem. Could you please update your veloxchem using the following command and try your molecule again?

`conda update -c conda-forge -c veloxchem veloxchem`

**Comment by bc118** [comment]
Yes, thanks, this fixed that issue.

**Comment by bc118** [comment]
I have tried to run dihedral fits for a protonated and non-protonated (COO-  and COOH) set.  COOH seems to match previous Gaussian results (except maybe the 0 point which is high), but the COO- one either does not converge or yeilds the wrong answer.  

The COOH one, just seem to not optimize correctly on the 0 degree angle of the dihedral

Can you clarify here?  Maybe I made a silly mistake? 

Note: Before updating the voloxchem package above, it would not even run the  COO- one without errors.  Therefore, is there an error somewhere with negatively charged molecules?

I have attached the mulitpsi code and results.

Note: the top plot contains both CT-CT-C-O, even though it is mislabeled as CT-CT-C-OH. The Gaussian data is also UHF without the MP2 correction, while the multipsi data is RHF with the MP2 correction.  The multipsi results are also output in Guassian form.

x-axis is Degrees, and y-axis is normalized energy in kcal/mol

![1](https://github.com/kthpanor/echem/assets/65550266/4e698548-870a-4a82-b1b3-95576bd85d61)

**Comment by recoli** [comment]
I can suggest the following:

1. Use a starting geometry where the two sp3 carbon atoms are in staggered conformation. Below is the one I tried:

```
10

C        0.0337034575   -0.1086811420    0.0427641645
C       -1.4747539126   -0.1058371522    0.0236413813
C       -2.1001591750    1.2797912449   -0.0416589728
O        0.7098881566   -1.1032942688    0.0647787738
O        0.5714657313    1.1160940523    0.0349235207
H       -1.7838208655   -0.7116937898   -0.8317408664
H       -1.8042866464   -0.6364021449    0.9206208384
H       -1.8049139852    1.8743165034    0.8185393457
H       -1.7828318880    1.8011575533   -0.9406323277
H       -3.1839782014    1.1956443254   -0.0518978296
```

2. Try the following code in your loop. Please note that (1) "molecule_xyz_input_file_name" should be in XYZ format, i.e. with number of atoms in the first line, (2) "dihedral_angle_degrees_list" should start with a value that is close to the dihedral angle in the starting geometry (e.g. 0 for the above geometry), and (3) the following code only runs MP2 for restricted SCF. Unrestricted MP2 will be available in the next weekly conda build of veloxchem. I'll get back with an updated version of the following code when the next conda build is ready.

```
    mol_vlx = vlx.Molecule.read_xyz_file(molecule_xyz_input_file_name)
    mol_vlx.set_charge(molecule_charge)
    mol_vlx.set_multiplicity(molecule_multiplicity)

    bas_vlx = vlx.MolecularBasis.read(mol_vlx, basis_set)

    scf_drv = ...
    grad_drv = vlx.ScfGradientDriver()
    opt_drv = vlx.OptimizationDriver(grad_drv)
    mp2_drv = vlx.Mp2Driver()

    dihedral_angle_degrees_list = ...

    for dihedral_angle_no_j, dihedral_angle_j in enumerate(dihedral_angle_degrees_list):

        dihedral_scan = ...
        opt_drv.constraints = ["$scan", dihedral_scan]

        mol_vlx = opt_drv.compute(mol_vlx, bas_vlx, scf_drv)
        mol_vlx.set_charge(molecule_charge)
        mol_vlx.set_multiplicity(molecule_multiplicity)

        scf_results = scf_drv.compute(mol_vlx, bas_vlx)
        scf_energies = {"HF": scf_results["scf_energy"]}

        if add_mp2_correction:
            if qm_method == "RC":
                mp2_results = mp2_drv.compute(mol_vlx, bas_vlx, scf_drv.mol_orbs)
                ...
            else:
                ...  # print error message
        else:
            ...
```

**Comment by bc118** [comment]
Thanks for your suggestions.  I will definitely update the molecule to use past optimized geometries.

However, you should not need to start in a particular geometry, that is the whole purpose of the minimizing function (changing geometry may make minimization faster though).  For example, all the other charged 0 simulations I ran (protonated) start in identical geometric configuration, except the H in COOH (added H atom), and they all run fine.  I believe there is something wrong with the minimizing function with charged molecules, and for the initial geometry.

I don’t see your plots to show that it even works to optimize with your suggestions.  Please provide your fit as (plots) of my code to the charged molecule using the optimize function, because it takes 2-3 days to run.    

This code is also very slow to optimize, so manually configuration of geometries after days of running to compensate for an issue with the minimizer is not an ideal solution, and may be harder when setting up dihedral energy calculations.  

Note: Gaussian does not have any of these issues, as I ran the identical geometries.  This is another reason I believe the issue is with the minimizer for charged molecules. 

If you want, run my test cases using my code or your own multi psi code and fit the dihedrals, compare the the Gaussian fits I provided, and see how it is not minimizing the charged molecules correctly .

**Comment by recoli** [comment]
Sorry for not being clear in my previous suggestions.

1. Change of starting geometry is only needed for dihedral angle of 0 degree. The purpose is to help the molecule escape from CT-CT saddle point and therefore eliminate imaginary frequency.

2. The following changes in the dihedral_scan code are necessary for producing correct MP2 energies for charged molecule (also recommended for neutral molecule)

   ```
        mol_vlx = opt_drv.compute(mol_vlx, bas_vlx, scf_drv)
        # the following two lines are workaround for charged molecule
        mol_vlx.set_charge(molecule_charge)
        mol_vlx.set_multiplicity(molecule_multiplicity)

        scf_results = scf_drv.compute(mol_vlx, bas_vlx)
        if add_mp2_correction:
            if qm_method == "RC":
                mp2_results = mp2_drv.compute(mol_vlx, bas_vlx, scf_drv.mol_orbs)
            # unrestricted MP2 will be available in future version
            else:
                ...
        else:
            ...
   ```

   The above code does three things:
   (1) Progressively update mol_vlx to ensure a smooth scan of geometry
   (2) Assign charge and multiplicity to mol_vlx (workaround for charged molecule) 
   (3) Run SCF prior to MP2 to make sure that mol, bas, mol_orbs, etc. are consistent

   We'll also add a fix on the veloxchem side so that workaround (2) will not be needed in future version.

3. For this particular molecule you do not need to rerun the optimization since the majority of the optimized geometries are correct. I checked those geometries (dihedral_coords_position_*.txt) by running single-point calculations and the results are summarized in the attached file. The potential energy curve looks very reasonable except for 0 degree (due to CT-CT saddle point) and -170 degree (which has a weird final geometry, possibly due to applying a constraint of -170 degree on a starting geometry with dihedral angle of 0 degree). I do not expect these issues to reappear after the starting geometry and dihedral_scan code are updated.
[CT_CT_C_3_O2__mult_1_energies.txt](https://github.com/kthpanor/echem/files/11867401/CT_CT_C_3_O2__mult_1_energies.txt)

Hope this makes more sense now. Thank you for spending time looking into this and for reporting the issue.

**Comment by bc118** [comment]
Hello!

Thanks.  I will try your suggestions next weekend.  I think what you are saying makes sense now.  Upon reevaluation of the Gaussian input, I did start the same molecule geometry at 0 angle and the 1st point (0 degrees) was unusable, then 10 degrees to 360 (steps of 10), where the 360 point was used for 0 and correct.  I believe you are saying this is the same issue and would work the here for multi psi?

Your suggestion on reusing the optimized geometry is good, and will likely speed up the code.  Thanks for noting I need to reapply the multiplicity and charges for now.

Based on your comments about geometry.  May I suggest an alternative auto fix for later versions?  Maybe use the MM UFF force field to minimize the initial geometry as an option.  While fixing the atoms in the dihedral.  This should avoid the issues you are saying and allow any starting geometry.  Maybe this can be don’t inside your code or via openMM directly for individual users.

**Comment by kthpanor** [comment]
THanks, I now got to your response in the pile of unread emails. Wasn’t sure you had seen it. Now I now. Sorry for the duplicate. /Patrick.

> On 25 Jun 2023, at 23:42, Xin Li ***@***.***> wrote:
> 
> 
> I can suggest the following:
> 
> 	• Use a starting geometry where the two sp3 carbon atoms are in staggered conformation. Below is the one I tried:
> 10
> 
> C        0.0337034575   -0.1086811420    0.0427641645
> C       -1.4747539126   -0.1058371522    0.0236413813
> C       -2.1001591750    1.2797912449   -0.0416589728
> O        0.7098881566   -1.1032942688    0.0647787738
> O        0.5714657313    1.1160940523    0.0349235207
> H       -1.7838208655   -0.7116937898   -0.8317408664
> H       -1.8042866464   -0.6364021449    0.9206208384
> H       -1.8049139852    1.8743165034    0.8185393457
> H       -1.7828318880    1.8011575533   -0.9406323277
> H       -3.1839782014    1.1956443254   -0.0518978296
> 
> 	• Try the following code in your loop. Please note that (1) "molecule_xyz_input_file_name" should be in XYZ format, i.e. with number of atoms in the first line, (2) "dihedral_angle_degrees_list" should start with a value that is close to the dihedral angle in the starting geometry (e.g. 0 for the above geometry), and (3) the following code only runs MP2 for restricted SCF. Unrestricted MP2 will be available in the next weekly conda build of veloxchem. I'll get back with an updated version of the following code when the next conda build is ready.
>     mol_vlx = vlx.Molecule.read_xyz_file(molecule_xyz_input_file_name)
>     mol_vlx.set_charge(molecule_charge)
>     mol_vlx.set_multiplicity(molecule_multiplicity)
> 
>     bas_vlx = vlx.MolecularBasis.read(mol_vlx, basis_set)
> 
>     scf_drv = ...
>     grad_drv = vlx.ScfGradientDriver()
>     opt_drv = vlx.OptimizationDriver(grad_drv)
>     mp2_drv = vlx.Mp2Driver()
> 
>     dihedral_angle_degrees_list = ...
> 
>     for dihedral_angle_no_j, dihedral_angle_j in enumerate(dihedral_angle_degrees_list):
> 
>         dihedral_scan = ...
>         opt_drv.constraints = ["$scan", dihedral_scan]
> 
>         mol_vlx = opt_drv.compute(mol_vlx, bas_vlx, scf_drv)
>         mol_vlx.set_charge(molecule_charge)
>         mol_vlx.set_multiplicity(molecule_multiplicity)
> 
>         scf_results = scf_drv.compute(mol_vlx, bas_vlx)
>         scf_energies = {"HF": scf_results["scf_energy"]}
> 
>         if add_mp2_correction:
>             if qm_method == "RC":
>                 mp2_results = mp2_drv.compute(mol_vlx, bas_vlx, scf_drv.mol_orbs)
>                 ...
>             else:
>                 ...  # print error message
>         else:
>             ...
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

-- 
---------------------------------------------------------------------------
Patrick Norman                                    e-mail: ***@***.***
Division of Theoretical Chemistry and Biology     phone : +46 8 790 96 31
KTH Royal Institute of Technology                 mobile: +46 73 765 2253
SE-100 44 Stockholm, Sweden
Homepage: https://www.kth.se/che/tcb/
---------------------------------------------------------------------------

**Comment by recoli** [comment]
> Hello!
> 
> Thanks. I will try your suggestions next weekend. I think what you are saying makes sense now. Upon reevaluation of the Gaussian input, I did start the same molecule geometry at 0 angle and the 1st point (0 degrees) was unusable, then 10 degrees to 360 (steps of 10), where the 360 point was used for 0 and correct. I believe you are saying this is the same issue and would work the here for multi psi?
> 
> Your suggestion on reusing the optimized geometry is good, and will likely speed up the code. Thanks for noting I need to reapply the multiplicity and charges for now.
> 
> Based on your comments about geometry. May I suggest an alternative auto fix for later versions? Maybe use the MM UFF force field to minimize the initial geometry as an option. While fixing the atoms in the dihedral. This should avoid the issues you are saying and allow any starting geometry. Maybe this can be don’t inside your code or via openMM directly for individual users.

1. Yes if the optimized geometry is reused as the starting geometry for the next step.

2. It is a good idea to use a faster method to pre-optimize the molecule, which will likely speed up the calculation. In veloxchem one could use the xTB method ([Semiempirical Extended Tight-Binding](https://github.com/grimme-lab/xtb)) for pre-optimization, for example

```
    xtb_drv = vlx.XtbDriver()
    xtb_grad_drv = vlx.XtbGradientDriver()
    xtb_opt_drv = vlx.OptimizationDriver(xtb_grad_drv)

    ...

    dihedral_angle_degrees_list = ...

    for dihedral_angle_no_j, dihedral_angle_j in enumerate(dihedral_angle_degrees_list):

        dihedral_scan = ...

        # pre-optimize using xTB
        xtb_opt_drv.constraints = ["$scan", dihedral_scan]
        mol_vlx = xtb_opt_drv.compute(mol_vlx, xtb_drv)
        mol_vlx.set_charge(molecule_charge)
        mol_vlx.set_multiplicity(molecule_multiplicity)

        # optimize using SCF
        scf_opt_drv.constraints = ["$scan", dihedral_scan]
        mol_vlx = scf_opt_drv.compute(mol_vlx, bas_vlx, scf_drv)
        mol_vlx.set_charge(molecule_charge)
        mol_vlx.set_multiplicity(molecule_multiplicity)

        ...
```

**Comment by bc118** [comment]
Ok these suggestions work and it is providing a correct energy for the dihedrals, even on the starting point, so thank you for your suggestions.  I never had to worry about these same stability issues in MM, so it was not obvious to me. 

Using the pre-optimize on every dihedral angle and using the last dihedral angle for the next dihedral angle is 3x faster than not doing it.  I am testing only to do the pre optimize on the 1st step now to see if it is faster or slower.   

While I wish multipsi was faster, likely will be as the code matures, I find the general purposing in Python, number of available basis sets, features, and even the initial documentation to be helpful.  I believe it will be useful to me for fitting missing MM parameters.  I hope you will continue to increase code performance, and I see you are still adding to the documentation, which is awesome.  

Thank you for your help.  Note: I am putting together a package to translate QM dihedrals into MM dihedrals, accounting for all the other interactions in the MM FFs; it is not a simple 1:1 transfer.
