### ISSUE TITLE
In future, improve code optimization performance 

### ISSUE THREAD

**Issue by bc118** [kthpanor/echem#11]
Hello,

This code is very easy to use and has many cool and easy to use features.  I am currently using it.  If you can enhance code performance, especially around the molecule optimization, this code would be much better.  This would also allow larger molecules to be used in an efficient manner.  

I see you are currently adding more documentation, which is also great.

I give it a huge thumbs up for the initial research though!!

**Comment by recoli** [comment]
Thank you very much for your positive feedback! Efficient geometric optimization is indeed an important feature; we are working on an improved version of the code that will perform better in this aspect, and will post an update here when there is progress.

**Comment by bc118** [comment]
Great!  That sounds good!  Thanks again!

**Comment by kthpanor** [comment]
All the best.
