### ISSUE TITLE
Feature request: Add CHELPG charge calculations

### ISSUE THREAD

**Issue by bc118** [kthpanor/echem#12]
Feature request: Add CHELPG charge calculations

Many of the MM force fields and researchers prefer to use CHELPG charge calculations to fit atomic charges.  Therefore, in future versions, adding this makes this code even better!

**Additionally, add charge restraints that fix the charges to be the same for similar atoms.**  
- Example: Restrain the Carbons with the same charge and Restrain all the Hydrogens with the same charge in ethane, as this would also be a great inclusion in CHELPG and other charge fits.  NWChem does this for a reference [(https://www.google.com/url?hl=en&q=https://github.com/nwchemgit/nwchem/blob/master/QA/tests/esp/esp.nw&source=gmail&ust=1693142561386000&usg=AOvVaw2la-zqm34XhNp7BZE1Aat7)]).  

I look forward to using your code in the future!

**Comment by recoli** [comment]
CHELPG ESP charges are now available with the latest ``veloxchem``, with the possibility of adding constraints of equal charges. This is done by the ``compute`` method of the ``RespChargesDriver`` class. To compute CHELPG ESP charges, one needs to set ``grid_type`` to ``chelpg``, and optionally set ``equal_charges`` as shown in the following example. 

```
import veloxchem as vlx

xyz_string = """
8
ethane
C   -1.926    0.141    0.000
H   -2.068    0.762    0.881
H   -2.068    0.762   -0.881
H   -2.692   -0.631    0.000
C   -0.538   -0.479   -0.000
H   -0.396   -1.100    0.881
H   -0.396   -1.100   -0.881
H    0.227    0.293   -0.000
"""
basis_set_label = 'sto-3g'

molecule = vlx.Molecule.read_xyz_string(xyz_string)
#molecule.set_charge(0)
#molecule.set_multiplicity(1)
basis = vlx.MolecularBasis.read(molecule, basis_set_label, ostream=None)

esp_drv = vlx.RespChargesDriver()
#esp_drv.ostream.mute()  # silence the output
esp_drv.filename = 'my_esp_calc'
esp_drv.grid_type = 'chelpg'
esp_drv.equal_charges = '1=5, 2=3=4=6=7=8'
fitted_charges = esp_drv.compute(molecule, basis, 'esp')

print(fitted_charges)
```

**Comment by bc118** [comment]
Ok.  Even better, it is already available.  Thanks!
