### ISSUE TITLE
Support of angular momenta > 2

### ISSUE THREAD

**Issue by einseler** [kthpanor/echem#13]
I tried to do some test scf calculations with water and def2-tzvp, but the job freezes after the calculation of the Orthogonalization matrix.

It seems like this is caused by basis functions with angular momenta that are greater than 2. After manually removing the F function for oxygen in def2-tzvp, the calculations worked without issue.

I installed veloxchem using the echem.yml and conda.

**Comment by MGDelcey** [comment]
This is a known issue. VeloxChem is still in pre-release version and the support for f functions is not complete. This should be fixed fairly soon as we prepare for the full release.

**Comment by einseler** [comment]
Alright. Thanks for the quick reply.
