### ISSUE TITLE
Software not working with new veloxchem versions

### ISSUE THREAD

**Issue by bc118** [kthpanor/echem#16]
The following in the dihedral example https://kthpanor.github.io/echem/docs/mol_struct/forcefields.html fails and is marked, showing several errors, where some I figured out.

    The new veloxchem versions break it, for all but the 1st error (bad line) in the code below. This happens on Mac an Linux.

    I attached 2 Linux yml files (1 good build and 1 bad build), also 1 Mac good build yml file, which still works with the example (except the 1st error)

The error on AssertionError: OptimizationDriver: Invalid constraint $scan , I am not sure how to fix.

- You likely should check a lot of other ones.  I suggest putting in unit tests for all the code that run nightly, or it will not be very usable.

[yml_files.zip](https://github.com/user-attachments/files/16395255/yml_files.zip)

### Code Example on the website that is now failing:
import shutil
import numpy as np
import py3Dmol as p3d
import veloxchem as vlx
from matplotlib import pyplot as plt
from scipy.interpolate import interp1d
from scipy.optimize import curve_fit
from datetime import datetime
Set up the molecule and basis set

ethane_mol_str = """
C 0.0000000000 0.0000000000 0.7616375820
C 0.0000000000 0.0000000000 -0.7616375820
H 1.0145603421 0.0000000000 1.1557300969
H -0.5072801711 -0.8786350299 1.1557300969
H -0.5072801711 0.8786350299 1.1557300969
H 0.5072801711 -0.8786350299 -1.1557300969
H 0.5072801711 0.8786350299 -1.1557300969
H -1.0145603421 -0.0000000000 -1.1557300969
"""
Create veloxchem mol and basis objects

#mol_vlx = vlx.Molecule.read_molecule_string(ethane_mol_str) - (bad line)
mol_vlx = vlx.Molecule.read_str(ethane_mol_str) # - (good line)
bas_vlx = vlx.MolecularBasis.read(mol_vlx, "STO-3G")
scf_drv = vlx.ScfRestrictedDriver()
scf_results = scf_drv.compute(mol_vlx, bas_vlx)
Set up the gradient and optimization dirvers:

#grad_drv = vlx.ScfGradientDriver()  - (bad line)
grad_drv = vlx.ScfGradientDriver(scf_drv) # - (good line)
opt_drv = vlx.OptimizationDriver(grad_drv)

dihed_a = np.arange(0, 65, 5)
dihed_e = []
dihed_xyz = []
for dihedral in dihed_a:
dihedral_scan = "dihedral 3 1 2 6 {} {} 1".format(dihedral, dihedral)
opt_drv.constraints = ["$scan", dihedral_scan] # - (bad line)

# Run the scan

 opt_molecule = opt_drv.compute(mol_vlx, bas_vlx, scf_drv) # - (bad line) from line  'opt_drv.constraints = ["$scan", dihedral_scan] ' (Not sure how to fix)
dihed_xyz.append(opt_molecule.get_coordinates())
dihed_e.append(scf_drv.get_scf_energy())
convert to kJ/mol and shift to zero

dihed_e = 2600.0 * (np.array(dihed_e) - min(dihed_e))

**Comment by iubr** [comment]
Thank you for pointing this issue out! I have now fixed the problem. The corrected notebook is available here: https://kthpanor.github.io/echem/docs/mol_struct/forcefields.html

Specifically, the way to set up the constraints is:
```python
opt_drv.constraints = ["scan angle 2 1 3 60 180 24"]
```

We already have tests in place to make sure that the Jupyter notebooks run, however the notebooks which contain numerical gradients (such as the one with the issue) are not included in the tests because they are very slow. Instead, I was responsible to make sure that the gradient-related notebooks work and I obviously missed this notebook...

I will close the issue, but let me know if you encounter any further problems.

**Comment by bc118** [comment]
Ok.  Thanks!  I would suggest getting something that is very close to convergence and start there and set up for automatic testing, shift the angle like .001 or something.  Or this will happen a lot as dependencies change and are updated, it affects everyone that maintains code.   If it is close to converged, you could run it and check the outputs on 2 min or something . Ideally you want to test outputs for every case.  

Personally, I don’t do anything in Jupiter notebooks as far as automated testing.  IMO, they are only good for tutorials, or if you are troubleshooting and 1 part takes a takes a long time and you are waiting a lot.
