### ISSUE TITLE
How to change the setting of "OMP_NUM_THREADS"?

### ISSUE THREAD

**Issue by yu-ting-py** [kthpanor/echem#2]
I appreciate your work a lot. I can learn by doing with your Jupyter Book. (Ubuntu 22 LTS)

As I run "ir_raman_solutions.ipynb" with Jupyter lab, it shows:
![Screenshot](https://user-images.githubusercontent.com/42253517/168222781-287a064f-72be-4392-ba68-87f63f1487d4.png)

OMP_NUM_THREADS  = 16 maybe by default, but this will eat up all my CPU capacity. 

Could I change this with some commands?

Thanks!

**Comment by iubr** [comment]
Hi!

This is a default from veloxchem. To change it, you simply have to set OMP_NUM_THREADS to something else, before importing veloxchem. Try the following in/before the import cell:

```
%env OMP_NUM_THREADS=4
import veloxchem as vlx
...
```

I hope this helps!
/Iulia
