### ISSUE TITLE
Missing Package

### ISSUE THREAD

**Issue by timhockswender** [kthpanor/echem#4]
This was also posted on the VeloxChem site.
Greetings, I'm attempting to install the system on Win11 but it fails at:
conda install -c conda-forge -c veloxchem multipsi=0.0.1
Evidently conda can't find multipsi

"PackagesNotFoundError: The following packages are not available from current channels:

multipsi=0.0.1 "
Please advise.
Thanks,
Tim

**Comment by glibaniosr** [comment]
Hello Tim,

Are you trying to install directly using Windows Anaconda or are you using Linux Anaconda by means of Windows Subsystem for Linux (WSL)?

**Comment by timhockswender** [comment]
I am trying Windows Anaconda. The error message was generated by conda. 
Tim.

**Comment by glibaniosr** [comment]
There is no Multipsi package for Windows Anaconda, only for Linux Anaconda. Therefore, what I recommend you is to install and use Windows Subsystem for Linux (WSL) in Windows 11. You can find detailed installation instructions from both Ubuntu (the most common distribution, but there are other options) or Microsoft websites included in the links below.

https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-10#1-overview

https://docs.microsoft.com/en-us/windows/wsl/install

**Comment by timhockswender** [comment]
Ok, thanks for the info. I have installed WSL but not used it much. Now I have some incentive!
Regards,
Tim

**Comment by kthpanor** [comment]
A conda package for Multipsi is now available fornative Windows.
