### ISSUE TITLE
scfHessian

### ISSUE THREAD

**Issue by maksimovica** [kthpanor/echem#6]
There is no veloxchem.scfhessiandriver in veloxchem rc2, nor veloxchem.ScfHessianDriver function?
They were used echem/docs/mol_struct/impes_calc.ipynb and in echem/docs/tutorials/vib_ir_calc.ipynb.

scf Modules available are:
vlx.scfdriver          vlx.scfgradientdriver  vlx.scfrestopendriver  
vlx.scffirstorderprop  vlx.scfrestdriver      vlx.scfunrestdriver 
and functions:
vlx.ScfFirstOrderProperties(  vlx.ScfRestrictedDriver(      vlx.ScfUnrestrictedDriver(
vlx.ScfGradientDriver(        vlx.ScfRestrictedOpenDriver(

**Comment by iubr** [comment]
Could you check what conda build version of veloxchem you have? Some of the older conda builds didn't include `ScfHessianDriver`, but it should be available in the latest conda build. You can check your build version by running:

```
conda activate echem_kaist
conda list veloxchem
```
(Replace echem_kaist with the name of the conda environment where you made the installation)

The result should look something like:
```
packages in environment at /home/emi/miniconda3/envs/echem_kaist:

Name                Version         Build             Channel
veloxchem           1.0rc2          py39h5d5e4cb_64    veloxchem
```
I have build **`py39h5d5e4cb_64`** and this one includes `ScfHessianDriver`. You can update your version by using:

`conda update veloxchem`

I hope this helps!

Please let me know if this doesn't fix your problem,

Best wishes,
Iulia

**Comment by maksimovica** [comment]
I have downloaded from the [GitLab repository](https://gitlab.com/veloxchem/veloxchem):
Don't like conda. 
But thanks for the tip.

**Comment by maksimovica** [comment]
The environment  from the multipsi instalation "mtpenv", also works. 
My bad, I was convinced that  the latest source (and stable one) is on the git (gitlab).
