### ISSUE TITLE
How do you set the number of threads or cores for each job and run MPI?

### ISSUE THREAD

**Issue by bc118** [kthpanor/echem#9]
How do you set the number of threads or cores for each job?  Is there a command in `veloxchem`, `mulitpsi` or another to do this, as it is harder to build a `Python` script and set cores with the imports at the top?

I can set threads/cores via the below in the first lines of the python code: 

```
import os
number_of_cores = 4
os.environ["OMP_NUM_THREADS"] = f"{number_of_cores}" # export OMP_NUM_THREADS
```

How do you get it to run on MPI instead of OMP?

Additionally, is it possible to change the log file name to something else or at least the base (beginning) of the file name (Example: `veloxchem_opt_2023-06-19T16.18.37.constr.txt` -> `my_selected_filename.constr.txt`?

**Comment by recoli** [comment]
Sorry for late reply on this issue.

First of all, base name of the optimization log file can be changed by setting the ``filename`` attribute of the optimization driver:

```
opt_drv.filename = "myscan"
```

The number of OpenMP threads is determined by the ``OMP_NUM_THREADS`` environment variable and what we usually do is to set this environment variable prior to executing the Python script. (**Update**: In VeloxChem you can use ``vlx.set_omp_num_threads("8")`` to set ``OMP_NUM_THREADS`` to 8.)

VeloxChem supports hybrid MPI/OpenMP parallelization. When writing script for parallel execution via MPI, please note that the results of the drivers are available only on the master process (rank 0). Taking the SCF and MP2 drivers as an example:

```
scf_drv = vlx.ScfRestrictedDriver()
scf_results = scf_drv.compute(molecule, basis)

mp2_drv = vlx.Mp2Driver()
mp2_results = mp2_drv.compute(molecule, basis, scf_drv.mol_orbs)

if mp2_drv.rank == 0:
    print("SCF energy:", scf_results["scf_energy"])
    print("MP2 correlation energy:", mp2_results["mp2_energy"])
```

To get optimal performance out of hybrid MPI/OpenMP parallelization one may need to 1) test different combinations of number of MPI processes and number of OpenMP threads, and 2) look into the binding/pinning options in [this link](https://hpc-wiki.info/hpc/Binding/Pinning#Options_for_Binding_in_Open_MPI).

**Comment by recoli** [comment]
Update:

In VeloxChem you can do the following:

```
vlx.set_omp_num_threads("8")  # set OMP_NUM_THREADS to 8
```
